# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Reads the binary SPSS file
#'
#' @param filePath The full systempath to the dta file you want to import.
#' @import Rcpp
#' @export
spss <- function(filePath, debug) {
    .Call('readspss_spss', PACKAGE = 'readspss', filePath, debug)
}

