# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' creates a factor inspired by an idea of Kevin Ushey in the Rcpp gallery
#' http://gallery.rcpp.org/articles/fast-factor-generation/
#'
#' @param x vector
#' @param y charactervector with labels
#' @import Rcpp
#' @export
fast_factor <- function(x, y) {
    .Call('_readspss_fast_factor', PACKAGE = 'readspss', x, y)
}

#' Reads the binary SPSS file
#'
#' @param filePath The full systempath to the dta file you want to import.
#' @param debug print debug information
#' @import Rcpp
#' @export
por <- function(filePath, debug, encStr) {
    .Call('_readspss_por', PACKAGE = 'readspss', filePath, debug, encStr)
}

#' Reads the binary SPSS file
#'
#' @param filePath The full systempath to the dta file you want to import.
#' @param debug print debug information
#' @import Rcpp
#' @export
sav <- function(filePath, debug, encStr) {
    .Call('_readspss_sav', PACKAGE = 'readspss', filePath, debug, encStr)
}

