# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' split character vector at "="
#'
#' @param val_s CharacterVector
#' @import Rcpp
#' @export
boost_split <- function(val_s) {
    .Call(`_readspss_boost_split`, val_s)
}

#' creates a factor inspired by an idea of Kevin Ushey in the Rcpp gallery
#' http://gallery.rcpp.org/articles/fast-factor-generation/
#'
#' @param x vector
#' @param y charactervector with labels
#' @import Rcpp
#' @export
fast_factor <- function(x, y) {
    .Call(`_readspss_fast_factor`, x, y)
}

#' Reads the binary SPSS file
#'
#' @param filePath The full systempath to the dta file you want to import.
#' @param debug print debug information
#' @param encStr encoding string
#' @import Rcpp
#' @export
readpor <- function(filePath, debug, encStr) {
    .Call(`_readspss_readpor`, filePath, debug, encStr)
}

#' Reads the binary SPSS file
#'
#' @param filePath The full systempath to the dta file you want to import.
#' @param debug print debug information
#' @param encStr encoding string
#' @param ownEnc encoding provided by localeToCharset
#' @import Rcpp
#' @export
readsav <- function(filePath, debug, encStr, ownEnc) {
    .Call(`_readspss_readsav`, filePath, debug, encStr, ownEnc)
}

